# Generated by Django 4.0.4 on 2022-04-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_posts_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[{'Active', 'active'}, {'Draft', 'draft'}], default='active', max_length=10),
        ),
    ]
